"""
Django settings for nordichomes project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path #parte do vídeo:8:57 

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent
# __file__ contém o caminho do arquivo atual
# Path(__file__) cria um objeto Path com esse caminho
# .resolve() resolve o caminho absoluto, seguindo links simbólicos se houver
# .parent retorna o diretório pai do caminho atual
# this is the folder where we have the manage.py and the root of the folder

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mp0kl0f@lg_@kf#kl(vu4v#+%_5uvzca$cwv5xo8z0^&h*j9j+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# Configuração que define a URL para redirecionamento após o logout.
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

# Definindo o tempo de validade da sessão em segundos (86400 segundos correspondem a 24 horas).
SESSION_COOKIE_AGE = 86400
# Nome da chave usada para armazenar informações relacionadas ao carrinho de compras na sessão do usuário.
# Este identificador pode ser personalizado conforme necessário para o contexto do aplicativo.
CART_SESSION_ID = 'cart'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart',
    'core',
    'product',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nordichomes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'nordichomes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# Configuração para arquivos de mídia no Django
# Define a URL base para os arquivos de mídia.
# Isso é usado como prefixo nos caminhos dos arquivos de mídia nas páginas do seu site.
MEDIA_URL = '/media/'
# Define o caminho no sistema de arquivos onde os arquivos de mídia serão armazenados.
# BASE_DIR é uma constante que representa o diretório raiz do seu projeto Django.
# O caminho completo para os arquivos de mídia será BASE_DIR / 'MEDIA'.
MEDIA_ROOT = BASE_DIR / 'media/'
#Essas configurações são fundamentais ao lidar com arquivos de mídia em um projeto Django, 
# garantindo que os arquivos sejam servidos corretamente quando necessário. 

#parte do vídeo:11:44